const sampleUsers = [
    {
        name: "Abdul Qadir",
        email: "abdulQadir@example.com",
        password: "password123",
        address: "123 Main St, City",
        center: "SCS",
        enrollment_id: "22/10/jc/053",
        contact_no: "7999547500",
    },
    {
        name: "Emma Johnson",
        email: "emma.johnson@example.com",
        password: "emmaPassword",
        address: "456 Oak St, Town",
        center: "PQR",
        enrollment_id: "22/10/jc/057",
        contact_no: "1111111111",
    },
    {
        name: "Robert Miller",
        email: "robert.miller@example.com",
        password: "millerPass",
        address: "789 Pine St, Village",
        center: "LMN",
        enrollment_id: "22/10/jc/058",
        contact_no: "2222222222",
    },
    {
        name: "Sophia Brown",
        email: "sophia.brown@example.com",
        password: "sophiaPass",
        address: "101 Maple St, Suburb",
        center: "XYZ",
        enrollment_id: "22/10/jc/059",
        contact_no: "3333333333",
    },
    {
        name: "Michael Davis",
        email: "michael.davis@example.com",
        password: "michaelPass",
        address: "202 Birch St, District",
        center: "ABC",
        enrollment_id: "22/10/jc/060",
        contact_no: "4444444444",
    },
    {
        name: "Ethan Anderson",
        email: "ethan.anderson@example.com",
        password: "ethanPass",
        address: "303 Cedar St, County",
        center: "LMN",
        enrollment_id: "22/10/jc/067",
        contact_no: "1111222233",
    },
    {
        name: "Olivia Miller",
        email: "olivia.miller@example.com",
        password: "oliviaPass",
        address: "404 Pine St, Province",
        center: "PQR",
        enrollment_id: "22/10/jc/068",
        contact_no: "4444555566",
    },
    {
        name: "Noah Davis",
        email: "noah.davis@example.com",
        password: "noahPass",
        address: "505 Maple St, Territory",
        center: "XYZ",
        enrollment_id: "22/10/jc/069",
        contact_no: "7777888899",
    },
    {
        name: "Ava Smith",
        email: "ava.smith@example.com",
        password: "avaPass",
        address: "606 Birch St, Region",
        center: "ABC",
        enrollment_id: "22/10/jc/070",
        contact_no: "1234123412",
    },
    {
        name: "Liam Taylor",
        email: "liam.taylor@example.com",
        password: "liamPass",
        address: "707 Cedar St, Domain",
        center: "SCS",
        enrollment_id: "22/10/jc/071",
        contact_no: "5678567856",
    },
    {
        name: "Sophia Wilson",
        email: "sophia.wilson@example.com",
        password: "wilsonPass",
        address: "808 Pine St, Territory",
        center: "LMN",
        enrollment_id: "22/10/jc/072",
        contact_no: "9090909090",
    },
    {
        name: "Jackson Brown",
        email: "jackson.brown@example.com",
        password: "jacksonPass",
        address: "909 Maple St, Region",
        center: "XYZ",
        enrollment_id: "22/10/jc/073",
        contact_no: "1212121212",
    },
    {
        name: "Emma White",
        email: "emma.white@example.com",
        password: "emmaWhitePass",
        address: "1010 Birch St, Suburb",
        center: "ABC",
        enrollment_id: "22/10/jc/074",
        contact_no: "3434343434",
    },
    {
        name: "Aiden Johnson",
        email: "aiden.johnson@example.com",
        password: "aidenPass",
        address: "1111 Cedar St, County",
        center: "PQR",
        enrollment_id: "22/10/jc/075",
        contact_no: "5656565656",
    },
    {
        name: "Mia Davis",
        email: "mia.davis@example.com",
        password: "miaPass",
        address: "1212 Pine St, Province",
        center: "SCS",
        enrollment_id: "22/10/jc/076",
        contact_no: "7878787878",
    },
];

module.exports = {data: sampleUsers};
